# Generated by Django 4.2.9 on 2025-01-02 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('swift_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('condition', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('SP', 'Spouse'), ('CH', 'Child'), ('PR', 'Parent'), ('SB', 'Sibling')], max_length=2)),
                ('date_of_birth', models.DateField()),
                ('is_sponsored', models.BooleanField(default=False)),
                ('documents', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PP', 'Passport'), ('VS', 'Visa'), ('CPR', 'CPR Card'), ('CNT', 'Contract'), ('CRT', 'Certificate'), ('OTH', 'Other')], max_length=3)),
                ('document_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeOffence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('action_taken', models.TextField()),
                ('warning_letter', models.FileField(blank=True, upload_to='warning_letters/')),
            ],
        ),
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MAR', 'Marriage'), ('CHD', 'Child Birth'), ('DEA', 'Death in Family'), ('OTH', 'Other')], max_length=3)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('documents', models.FileField(blank=True, upload_to='life_event_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeskill',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_number']},
        ),
        migrations.AlterModelOptions(
            name='employeeeducation',
            options={},
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='base_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_hired',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='DEPT', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='accom_occu_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bond_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_accommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('INT', 'Intern')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cost_center',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cpr_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_category',
            field=models.CharField(blank=True, choices=[('STF', 'Staff'), ('WRK', 'Worker'), ('MGR', 'Manager'), ('EXE', 'Executive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(default='EMP0001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='First', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='guarantee_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='in_probation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Last', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_accrual_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notice_period',
            field=models.IntegerField(default=30, help_text='In days'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payroll_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_period',
            field=models.IntegerField(default=90, help_text='In days'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession_cpr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profit_center',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='rejoined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_allowances',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_deductions',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_cr_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='graduation_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='major',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='degree',
            field=models.CharField(default='Unknown Degree', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='institution',
            field=models.CharField(default='Unknown Institution', max_length=100),
        ),
        migrations.DeleteModel(
            name='EmployeeExperience',
        ),
        migrations.DeleteModel(
            name='EmployeeSkill',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeoffence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offences', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeedependent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='division',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.bank'),
        ),
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.division'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.location'),
        ),
    ]
