# Generated by Django 4.2.9 on 2025-01-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeoffence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
