from django.db import migrations

def convert_penalty_to_code(penalty):
    penalty_map = {
        'Oral Warning': 'ORAL',
        'Written Warning': 'WRITTEN',
        '0.05': 'D005',
        '0.10': 'D010',
        '0.15': 'D015',
        '0.25': 'D025',
        '0.50': 'D050',
        '0.75': 'D075',
        '1': 'D100',
        '2': 'D200',
        '3': 'D300',
        '5': 'D500',
        'Dismissal': 'DISMISSAL',
    }
    return penalty_map.get(penalty, penalty)

def add_initial_offense_rules(apps, schema_editor):
    OffenseRule = apps.get_model('employees', 'OffenseRule')

    rules = [
        {
            'rule_id': '1.1',
            'group': 'ATTENDANCE_TIME',
            'name': 'Tardiness - Up to 15 Min (No Disruption)',
            'description': "Reporting late up to 15 minutes beyond the attendance time without permission or a valid excuse, where the delay doesn't hamper other workers.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.05'),
            'fourth_penalty': convert_penalty_to_code('0.10'),
            'remarks': '',
        },
        {
            'rule_id': '1.2',
            'group': 'ATTENDANCE_TIME',
            'name': 'Tardiness - Up to 15 Min (With Disruption)',
            'description': "Reporting late up to 15 minutes beyond the attendance time without permission or a valid excuse, resulting in the disruption of other workers.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '1.3',
            'group': 'ATTENDANCE_TIME',
            'name': 'Tardiness - 15 to 30 Min (No Disruption)',
            'description': "Reporting late more than 15 minutes but up to 30 minutes beyond the attendance time without permission or valid excuse, where the delay doesn't hamper other workers.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.15'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '1.4',
            'group': 'ATTENDANCE_TIME',
            'name': 'Tardiness - 15 to 30 Min (With Disruption)',
            'description': "Reporting late more than 15 minutes but up to 30 minutes beyond the attendance time without permission or valid excuse, resulting in the disruption of other workers.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.50'),
            'third_penalty': convert_penalty_to_code('0.75'),
            'fourth_penalty': convert_penalty_to_code('1'),
            'remarks': '',
        },
        {
            'rule_id': '1.5',
            'group': 'ATTENDANCE_TIME',
            'name': 'Tardiness - 30 to 60 Min (No Disruption)',
            'description': "Reporting late more than 15 minutes and up to 60 minutes beyond the attendance time without permission or a valid excuse, where the delay doesn't disrupt other workers.",
            'first_penalty': convert_penalty_to_code('0.25'),
            'second_penalty': convert_penalty_to_code('0.50'),
            'third_penalty': convert_penalty_to_code('0.75'),
            'fourth_penalty': convert_penalty_to_code('1'),
            'remarks': '',
        },
        {
            'rule_id': '1.6',
            'group': 'ATTENDANCE_TIME',
            'name': 'Tardiness - 30 to 60 Min (With Disruption)',
            'description': "Reporting late more than 15 minutes and up to 60 minutes beyond the attendance time without permission or a valid excuse, where the delay disrupts other workers.",
            'first_penalty': convert_penalty_to_code('0.30'),
            'second_penalty': convert_penalty_to_code('0.50'),
            'third_penalty': convert_penalty_to_code('0.75'),
            'fourth_penalty': convert_penalty_to_code('2'),
            'remarks': '',
        },
        {
            'rule_id': '1.7',
            'group': 'ATTENDANCE_TIME',
            'name': 'Tardiness - Over 60 Min',
            'description': "Reporting late more than one hour beyond the attendance time without permission or a valid excuse, where the delay does not result in hampering other workers.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('1'),
            'third_penalty': convert_penalty_to_code('2'),
            'fourth_penalty': convert_penalty_to_code('3'),
            'remarks': 'In addition to deducting delay hours.',
        },
        {
            'rule_id': '1.8',
            'group': 'ATTENDANCE_TIME',
            'name': 'Early Departure - Up to 15 Min',
            'description': "Leaving work early, no more than 15 minutes prior to the set hour without permission or a valid excuse.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.10'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('1'),
            'remarks': '',
        },
        {
            'rule_id': '1.9',
            'group': 'ATTENDANCE_TIME',
            'name': 'Early Departure - Over 15 Min',
            'description': "Leaving work early, more than 15 minutes prior to the leaving hour without permission or a valid excuse.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.10'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('1'),
            'remarks': 'In addition to deducting delay hours.',
        },
        {
            'rule_id': '1.10',
            'group': 'ATTENDANCE_TIME',
            'name': 'Unauthorized Overstay',
            'description': "Staying at work or returning to work after the working hours without a reasonable excuse.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.10'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('1'),
            'remarks': '',
        },
        {
            'rule_id': '2.1',
            'group': 'WORK_ORG',
            'name': 'Unauthorized Exit Use',
            'description': "Getting out from any exit other than those designated for this purpose.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.15'),
            'fourth_penalty': convert_penalty_to_code('0.25'),
            'remarks': '',
        },
        {
            'rule_id': '2.2',
            'group': 'WORK_ORG',
            'name': 'Unauthorized Visitors',
            'description': "Receiving visitors other than organization’s workers at the workplace without permission from management.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.15'),
            'fourth_penalty': convert_penalty_to_code('0.25'),
            'remarks': '',
        },
        {
            'rule_id': '2.3',
            'group': 'WORK_ORG',
            'name': 'Unauthorized Eating',
            'description': "Eating in any place or at any time other than those set for this purpose.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.15'),
            'fourth_penalty': convert_penalty_to_code('0.25'),
            'remarks': '',
        },
        {
            'rule_id': '2.4',
            'group': 'WORK_ORG',
            'name': 'Sleeping on Duty',
            'description': "Falling asleep during the working hours.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '2.5',
            'group': 'WORK_ORG',
            'name': 'Unauthorized Phone Use',
            'description': "Using organization's telephone for private purposes without permission.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '2.6',
            'group': 'WORK_ORG',
            'name': 'Loitering',
            'description': "Loitering or being caught anywhere other than set places during working hours.",
            'first_penalty': convert_penalty_to_code('0.10'),
            'second_penalty': convert_penalty_to_code('0.25'),
            'third_penalty': convert_penalty_to_code('0.50'),
            'fourth_penalty': convert_penalty_to_code('1'),
            'remarks': '',
        },
        {
            'rule_id': '2.7',
            'group': 'WORK_ORG',
            'name': 'Attendance Sheet Manipulation',
            'description': "Manipulation of the attendance sheet.",
            'first_penalty': convert_penalty_to_code('0.25'),
            'second_penalty': convert_penalty_to_code('0.50'),
            'third_penalty': convert_penalty_to_code('1'),
            'fourth_penalty': convert_penalty_to_code('2'),
            'remarks': '',
        },
        {
            'rule_id': '2.8',
            'group': 'WORK_ORG',
            'name': 'Disobeying Workflow Orders',
            'description': "Disobeying regular orders related to the workflow.",
            'first_penalty': convert_penalty_to_code('0.25'),
            'second_penalty': convert_penalty_to_code('0.50'),
            'third_penalty': convert_penalty_to_code('1'),
            'fourth_penalty': convert_penalty_to_code('2'),
            'remarks': '',
        },
        {
            'rule_id': '2.9',
            'group': 'WORK_ORG',
            'name': 'Failure to Follow Instructions',
            'description': "Failure to perform instructions related to workflow, provided those instructions are posted in a visible place.",
            'first_penalty': convert_penalty_to_code('0.25'),
            'second_penalty': convert_penalty_to_code('0.50'),
            'third_penalty': convert_penalty_to_code('1'),
            'fourth_penalty': convert_penalty_to_code('2'),
            'remarks': '',
        },
        {
            'rule_id': '2.10',
            'group': 'WORK_ORG',
            'name': 'Sleeping on Duty (Critical Role)',
            'description': "Falling asleep in a position or role that requires being permanently awake.",
            'first_penalty': convert_penalty_to_code('0.50'),
            'second_penalty': convert_penalty_to_code('1'),
            'third_penalty': convert_penalty_to_code('2'),
            'fourth_penalty': convert_penalty_to_code('3'),
            'remarks': '',
        },
        {
            'rule_id': '2.11',
            'group': 'WORK_ORG',
            'name': 'Incitement Against Instructions',
            'description': "Incitement against special instructions and orders.",
            'first_penalty': convert_penalty_to_code('2'),
            'second_penalty': convert_penalty_to_code('3'),
            'third_penalty': convert_penalty_to_code('5'),
            'fourth_penalty': convert_penalty_to_code('Dismissal'),
            'remarks': '',
        },
        {
            'rule_id': '2.12',
            'group': 'WORK_ORG',
            'name': 'Negligence Causing Harm',
            'description': "Neglect or negligence in work that causes harm to workers' health or safety, or damage to materials and tools.",
            'first_penalty': convert_penalty_to_code('2'),
            'second_penalty': convert_penalty_to_code('3'),
            'third_penalty': convert_penalty_to_code('5'),
            'fourth_penalty': convert_penalty_to_code('Dismissal'),
            'remarks': '',
        },
        {
            'rule_id': '2.13',
            'group': 'WORK_ORG',
            'name': 'Prohibited Substance Use',
            'description': "Smoking where it is forbidden to maintain workers' health, or drinking alcohol in the workplace.",
            'first_penalty': convert_penalty_to_code('2'),
            'second_penalty': convert_penalty_to_code('3'),
            'third_penalty': convert_penalty_to_code('5'),
            'fourth_penalty': convert_penalty_to_code('Dismissal'),
            'remarks': 'Worker may be dismissed if the violation results in gross damage',
        },
        {
            'rule_id': '3.1',
            'group': 'BEHAVIOR',
            'name': 'Unauthorized Fundraising',
            'description': "Raising funds or money without permission.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('0.10'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.2',
            'group': 'BEHAVIOR',
            'name': 'Unauthorized Posting',
            'description': "Posting on walls either by writing or taping ads.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.3',
            'group': 'BEHAVIOR',
            'name': 'Wasteful Material Consumption',
            'description': "Wasteful consumption of raw materials without permission.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.50'),
            'third_penalty': convert_penalty_to_code('1'),
            'fourth_penalty': convert_penalty_to_code('2'),
            'remarks': '',
        },
        {
            'rule_id': '3.4',
            'group': 'BEHAVIOR',
            'name': 'Misrepresentation Causing Dispute',
            'description': "Misrepresentation regarding seniors or peers in a way that results in suspending work or arising disputes internally within the Company.",
            'first_penalty': convert_penalty_to_code('0.25'),
            'second_penalty': convert_penalty_to_code('0.50'),
            'third_penalty': convert_penalty_to_code('1'),
            'fourth_penalty': convert_penalty_to_code('2'),
            'remarks': '',
        },
        {
            'rule_id': '3.5',
            'group': 'BEHAVIOR',
            'name': 'Refusal of Search',
            'description': "Refusal of search while leaving work.",
            'first_penalty': convert_penalty_to_code('0.25'),
            'second_penalty': convert_penalty_to_code('0.50'),
            'third_penalty': convert_penalty_to_code('1'),
            'fourth_penalty': convert_penalty_to_code('2'),
            'remarks': '',
        },
        {
            'rule_id': '3.6',
            'group': 'BEHAVIOR',
            'name': 'Violation of Health Instructions',
            'description': "Violation of health instructions while being at work.",
            'first_penalty': convert_penalty_to_code('0.50'),
            'second_penalty': convert_penalty_to_code('1'),
            'third_penalty': convert_penalty_to_code('2'),
            'fourth_penalty': convert_penalty_to_code('5'),
            'remarks': '',
        },
        {
            'rule_id': '3.7',
            'group': 'BEHAVIOR',
            'name': 'Unauthorized Use of Materials',
            'description': "Using objects, materials, and tools for private purposes.",
            'first_penalty': convert_penalty_to_code('1'),
            'second_penalty': convert_penalty_to_code('2'),
            'third_penalty': convert_penalty_to_code('3'),
            'fourth_penalty': convert_penalty_to_code('5'),
            'remarks': '',
        },
        {
            'rule_id': '3.8',
            'group': 'BEHAVIOR',
            'name': 'Quarrels and Rioting',
            'description': "Quarrelling with peers or creating quarrels while being at work, or rioting.",
            'first_penalty': convert_penalty_to_code('1'),
            'second_penalty': convert_penalty_to_code('2'),
            'third_penalty': convert_penalty_to_code('3'),
            'fourth_penalty': convert_penalty_to_code('5'),
            'remarks': '',
        },
        {
            'rule_id': '3.9',
            'group': 'BEHAVIOR',
            'name': 'Malingering',
            'description': "Malingering or the unapproved and undocumented use of sick leave. (Sick leaves need to be provided from government hospitals or clinics, or a private clinic or hospital approved by the company insurance provider, contingent on the use of medical insurance).",
            'first_penalty': convert_penalty_to_code('1'),
            'second_penalty': convert_penalty_to_code('2'),
            'third_penalty': convert_penalty_to_code('3'),
            'fourth_penalty': convert_penalty_to_code('5'),
            'remarks': '',
        },
        {
            'rule_id': '3.10',
            'group': 'BEHAVIOR',
            'name': 'Refusal of Medical Exam',
            'description': "Refusal of medical examination when requested by the organization's physician.",
            'first_penalty': convert_penalty_to_code('1'),
            'second_penalty': convert_penalty_to_code('2'),
            'third_penalty': convert_penalty_to_code('3'),
            'fourth_penalty': convert_penalty_to_code('5'),
            'remarks': '',
        },
        {
            'rule_id': '3.11',
            'group': 'BEHAVIOR',
            'name': 'Failure to Deliver Collected Money',
            'description': "Non-delivery of collected money into the organization account on time without a reasonable excuse.",
            'first_penalty': convert_penalty_to_code('2'),
            'second_penalty': convert_penalty_to_code('3'),
            'third_penalty': convert_penalty_to_code('5'),
            'fourth_penalty': convert_penalty_to_code('Dismissal'),
            'remarks': '',
        },
        {
            'rule_id': '3.12',
            'group': 'BEHAVIOR',
            'name': 'Violation of In-House Instructions',
            'description': "Violation of in-house instructions on work.",
            'first_penalty': convert_penalty_to_code('2'),
            'second_penalty': convert_penalty_to_code('3'),
            'third_penalty': convert_penalty_to_code('5'),
            'fourth_penalty': convert_penalty_to_code('Dismissal'),
            'remarks': '',
        },
        {
            'rule_id': '3.13',
            'group': 'BEHAVIOR',
            'name': 'Dress Code Violation',
            'description': "Not following the dress code required by the organization.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.10'),
            'fourth_penalty': convert_penalty_to_code('0.25'),
            'remarks': '',
        },
        {
            'rule_id': '3.14',
            'group': 'BEHAVIOR',
            'name': 'Failure to Complete Training',
            'description': "Failure to complete the training and development course.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.10'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.15',
            'group': 'BEHAVIOR',
            'name': 'Refusal to Attend Overtimes',
            'description': "Refusal to attend overtimes.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.16',
            'group': 'BEHAVIOR',
            'name': 'Unauthorized Transactions',
            'description': "Entering into purchase/sale transactions or the promotion of goods at the workplace.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.10'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.17',
            'group': 'BEHAVIOR',
            'name': 'Leaving Info Unattended',
            'description': "Leaving essential or confidential information unattended at the office or desk.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.18',
            'group': 'BEHAVIOR',
            'name': 'Leaving Info on Shared Device',
            'description': "Leaving essential or confidential information on the printer, photocopier, or fax machine.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.19',
            'group': 'BEHAVIOR',
            'name': 'Damage to Data Backups',
            'description': "Damaging data backups without permission from the organization’s management.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.10'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.20',
            'group': 'BEHAVIOR',
            'name': 'Failure to Report Theft',
            'description': "Failure to report any theft of a computer or related accessories.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.10'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.21',
            'group': 'BEHAVIOR',
            'name': 'Failure to Log Off Computer',
            'description': "Failure to log out and shut the computer down while being out of the office, unless otherwise required.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.22',
            'group': 'BEHAVIOR',
            'name': 'Misuse of Email',
            'description': "Misuse of email.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.23',
            'group': 'BEHAVIOR',
            'name': 'Trespassing/Assaulting Officials',
            'description': "Trespassing on or assaulting officials in any way.",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.10'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.24',
            'group': 'BEHAVIOR',
            'name': 'Tampering with Messages',
            'description': "Hiding, destroying, opening, or causing to be hidden, destroyed, or opened by third parties any message delivered to the mail (wired and wireless messages).",
            'first_penalty': convert_penalty_to_code('Written Warning'),
            'second_penalty': convert_penalty_to_code('0.10'),
            'third_penalty': convert_penalty_to_code('0.25'),
            'fourth_penalty': convert_penalty_to_code('0.50'),
            'remarks': '',
        },
        {
            'rule_id': '3.25',
            'group': 'BEHAVIOR',
            'name': 'Negligence with Data Backups',
            'description': "Negligence to keep a backup away from the computer or in a safe place.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.10'),
            'fourth_penalty': convert_penalty_to_code('0.25'),
            'remarks': '',
        },
        {
            'rule_id': '3.26',
            'group': 'BEHAVIOR',
            'name': 'Failure to Shut Down PC',
            'description': "Failure to shut down personal computers at the end of official working hours.",
            'first_penalty': convert_penalty_to_code('Oral Warning'),
            'second_penalty': convert_penalty_to_code('Written Warning'),
            'third_penalty': convert_penalty_to_code('0.10'),
            'fourth_penalty': convert_penalty_to_code('0.25'),
            'remarks': '',
        },
    ]

    for rule_data in rules:
        OffenseRule.objects.create(**rule_data)

def remove_initial_offense_rules(apps, schema_editor):
    OffenseRule = apps.get_model('employees', 'OffenseRule')
    rule_ids_to_remove = [
        '1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10',
        '2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '2.8', '2.9', '2.10', '2.11', '2.12', '2.13',
        '3.1', '3.2', '3.3', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14', '3.15', '3.16', '3.17', '3.18', '3.19', '3.20', '3.21', '3.22', '3.23', '3.24', '3.25', '3.26',
    ]
    OffenseRule.objects.filter(rule_id__in=rule_ids_to_remove).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0002_add_is_active_to_offense'),
    ]

    operations = [
        migrations.RunPython(add_initial_offense_rules, remove_initial_offense_rules),
    ]