# Generated by Django 4.2.9 on 2025-01-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_dependentdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Primary Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
