# Generated by Django 4.2.9 on 2025-01-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_initial_offense_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offenserule',
            name='group',
            field=models.CharField(choices=[('ATTENDANCE_TIME', 'Violations Concerning Attendance Time'), ('WORK_ORG', 'Violations Concerning Work Organization'), ('BEHAVIOR', 'Violations Concerning Employee Behavior'), ('SAFETY', 'Violations Concerning Safety'), ('PROPERTY', 'Violations Concerning Company Property'), ('OTHER', 'Other Violations')], max_length=20),
        ),
    ]
