# Generated by Django 4.2.9 on 2025-01-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='iban',
        ),
        migrations.AlterField(
            model_name='employee',
            name='accom_occu_date',
            field=models.DateField(blank=True, null=True, verbose_name='Accommodation Occupation Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bond_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_accrual_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notice_period',
            field=models.IntegerField(default=30, help_text='Notice period in days'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='EmployeeBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=50, verbose_name='IBAN No')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount to be Transferred')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Bank Account',
                'verbose_name_plural': 'Employee Bank Accounts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
