# Generated by Django 4.2.9 on 2025-01-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_account_number_remove_employee_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebankaccount',
            name='transfer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount to be Transferred'),
        ),
    ]
