# Generated by Django 4.2.9 on 2025-01-08 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_address_employee_primary_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee Asset', 'verbose_name_plural': 'Employee Assets'},
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='return_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
