# Generated by Django 4.2.9 on 2025-01-02 13:19

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeebankaccount_transfer_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee Document', 'verbose_name_plural': 'Employee Documents'},
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='notes',
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='issue_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='profession_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession / Title'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('RESIDENT', 'Resident Permit'), ('CPR', 'C.P.R'), ('GATE', 'Gate Pass'), ('CONTRACT', 'Contract'), ('CV', 'CV'), ('DRIVING', 'Driving License')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
