# Generated by Django 4.2.9 on 2025-01-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_assettype_employeeasset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeasset',
            name='return_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
