# Generated by Django 4.2.9 on 2025-01-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeedocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profession_cpr',
        ),
    ]
