# Generated by Django 4.2.9 on 2025-01-11 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeeasset_return_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeasset',
            name='asset_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeasset',
            name='condition',
            field=models.TextField(default='New'),
        ),
        migrations.AlterField(
            model_name='employeeasset',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeeasset',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
