# Generated by Django 4.2.9 on 2025-01-04 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_profession_cpr'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostProfitCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cost/Profit Center',
                'verbose_name_plural': 'Cost/Profit Centers',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='accom_occu_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bond_amount',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company_accommodation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_start_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='guarantee_details',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave_accrual_rate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='payroll_group',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rejoined_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sponsor_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='total_allowances',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='total_deductions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='visa_cr_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_pictures/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_category',
            field=models.CharField(blank=True, choices=[('GEN', 'General'), ('SUP', 'Supervisor'), ('MGR', 'Manager'), ('EXE', 'Executive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_center_employees', to='employees.costprofitcenter'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profit_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_center_employees', to='employees.costprofitcenter'),
        ),
    ]
