# Generated by Django 4.2.9 on 2025-01-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employeeasset_asset_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50, unique=True)),
                ('entered_on', models.DateField()),
                ('offence_type', models.CharField(choices=[('LATENESS', 'ACCEPTED lateness'), ('MISUSE', 'Misuse of Property'), ('MOBILE', 'USING MOBILE DURING DUTY HOURS'), ('ABSENT', 'ABSENT WITHOUT REASON'), ('LATE', 'LATNESS WITHOUT VALID REASON'), ('DAMAGE', 'PROPERTIES DAMAGE'), ('BAD_COWORKER', 'BAD ATTITUDE WITH CO-WORKERS'), ('BAD_CUSTOMER', 'BAD ATTITUDEWITH CUSTOMERS'), ('DISOBEY', 'NOT FOLLOWING ORDERS'), ('OTHER', 'Others')], max_length=20)),
                ('offence_type_other', models.CharField(blank=True, max_length=100, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_offences', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='employeeoffence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_offences', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='OffenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='offence_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('offence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.offence')),
            ],
        ),
    ]
