# Generated by Django 4.2.9 on 2025-02-04 00:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0009_alter_employeeoffence_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=2, help_text='Duration in days', max_digits=4)),
                ('start_half', models.BooleanField(default=False, help_text='True if starting with half day')),
                ('end_half', models.BooleanField(default=False, help_text='True if ending with half day')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('REGULAR', 'Regular Leave'), ('SPECIAL', 'Special Leave'), ('MEDICAL', 'Medical Leave')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('days_allowed', models.PositiveIntegerField(help_text='Number of days allowed per period')),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('gender_specific', models.CharField(choices=[('M', 'Male Only'), ('F', 'Female Only'), ('A', 'All')], default='A', max_length=1)),
                ('accrual_enabled', models.BooleanField(default=False)),
                ('accrual_days', models.DecimalField(blank=True, decimal_places=2, help_text='Days accrued per month/period', max_digits=4, null=True)),
                ('accrual_period', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('WORKED', 'Per Worked Days')], max_length=10, null=True)),
                ('reset_period', models.CharField(choices=[('YEARLY', 'Yearly'), ('NEVER', 'Never Reset'), ('EVENT', 'Per Event')], default='YEARLY', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_night_shift', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LeaveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='leave_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('document_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='attendance.leave')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='attendance.leave')),
            ],
            options={
                'verbose_name_plural': 'Leave activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='attendance.leavetype'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('PUBLIC', 'Public Holiday'), ('COMPANY', 'Company Holiday'), ('OPTIONAL', 'Optional Holiday')], default='PUBLIC', max_length=20)),
                ('is_recurring', models.BooleanField(default=False, help_text='If True, holiday repeats every year')),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_departments', models.ManyToManyField(blank=True, related_name='holidays', to='employees.department')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_in_time', models.TimeField()),
                ('last_out_time', models.TimeField()),
                ('source', models.CharField(choices=[('system', 'System'), ('manual', 'Manual')], default='system', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_logs', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_first_in', models.TimeField()),
                ('original_last_out', models.TimeField()),
                ('edited_first_in', models.TimeField()),
                ('edited_last_out', models.TimeField()),
                ('edit_timestamp', models.DateTimeField(auto_now_add=True)),
                ('edit_reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('attendance_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='attendance.attendancelog')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edit_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_accrual_date', models.DateField(blank=True, null=True)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_balances', to='attendance.leavetype')),
            ],
            options={
                'ordering': ['employee', 'leave_type'],
                'unique_together': {('employee', 'leave_type')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('device_name', models.CharField(max_length=100)),
                ('event_point', models.CharField(max_length=100)),
                ('verify_type', models.CharField(max_length=50)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('employee', 'timestamp')},
            },
        ),
    ]
