# Generated by Django 4.2.9 on 2025-01-26 13:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employeeoffence_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('REGULAR', 'Regular Leave'), ('SPECIAL', 'Special Leave'), ('MEDICAL', 'Medical Leave')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('days_allowed', models.PositiveIntegerField(help_text='Number of days allowed per period')),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('gender_specific', models.CharField(choices=[('M', 'Male Only'), ('F', 'Female Only'), ('A', 'All')], default='A', max_length=1)),
                ('accrual_enabled', models.BooleanField(default=False)),
                ('accrual_days', models.DecimalField(blank=True, decimal_places=2, help_text='Days accrued per month/period', max_digits=4, null=True)),
                ('accrual_period', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('WORKED', 'Per Worked Days')], max_length=10, null=True)),
                ('reset_period', models.CharField(choices=[('YEARLY', 'Yearly'), ('NEVER', 'Never Reset'), ('EVENT', 'Per Event')], default='YEARLY', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='leave',
            name='remarks',
        ),
        migrations.AddField(
            model_name='holiday',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, related_name='holidays', to='employees.department'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('PUBLIC', 'Public Holiday'), ('COMPANY', 'Company Holiday'), ('OPTIONAL', 'Optional Holiday')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='If True, holiday repeats every year'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Duration in days', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='end_half',
            field=models.BooleanField(default=False, help_text='True if ending with half day'),
        ),
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_half',
            field=models.BooleanField(default=False, help_text='True if starting with half day'),
        ),
        migrations.AddField(
            model_name='leave',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='leave_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('document_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='attendance.leave')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='attendance.leave')),
            ],
            options={
                'verbose_name_plural': 'Leave activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='attendance.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_accrual_date', models.DateField(blank=True, null=True)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_balances', to='attendance.leavetype')),
            ],
            options={
                'ordering': ['employee', 'leave_type'],
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
