# Generated by Django 4.2.9 on 2025-02-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial_leave_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('days_allowed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_documentation', models.BooleanField(default=False)),
                ('documentation_info', models.TextField(blank=True, help_text='What documents are required')),
                ('reset_frequency', models.CharField(choices=[('never', 'Never'), ('annually', 'Annually'), ('monthly', 'Monthly'), ('per_event', 'Per Event')], default='annually', max_length=20)),
                ('gender_specific', models.CharField(choices=[('M', 'Male Only'), ('F', 'Female Only'), ('A', 'All')], default='A', max_length=1)),
                ('min_service_months', models.PositiveIntegerField(default=0)),
                ('max_days_per_request', models.PositiveIntegerField(blank=True, null=True)),
                ('min_days_per_request', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('notice_days_required', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
