# Generated by Django 4.2.9 on 2025-02-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leaverule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='early_departure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='early_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave'), ('holiday', 'Holiday')], default='absent', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='total_work_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='first_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='last_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
