# Generated by Django 4.2.9 on 2025-02-11 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0006_add_shift_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('DEFAULT', 'Default Shift (7AM-4PM)'), ('NIGHT', 'Night Shift'), ('OPEN', 'Open Shift')], default='DEFAULT', max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
