# Generated by Django 4.2.9 on 2025-02-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_shift_shift_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='default_night_end_time',
            field=models.TimeField(blank=True, help_text='Default end time for night shift', null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='default_night_start_time',
            field=models.TimeField(blank=True, help_text='Default start time for night shift', null=True),
        ),
    ]
