# Generated by Django 4.2.9 on 2025-02-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_shift_default_night_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSpecificShiftOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which shift is overridden', unique=True)),
                ('shift_type', models.CharField(choices=[('DEFAULT', 'Default Shift (7AM-4PM)'), ('NIGHT', 'Night Shift'), ('OPEN', 'Open Shift')], default='NIGHT', help_text='Shift type to override', max_length=20)),
                ('override_start_time', models.TimeField(blank=True, help_text='Override start time', null=True)),
                ('override_end_time', models.TimeField(blank=True, help_text='Override end time', null=True)),
            ],
            options={
                'verbose_name': 'Shift Override',
                'verbose_name_plural': 'Shift Overrides',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='shift',
            name='default_night_end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='default_night_start_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='is_night_shift',
        ),
        migrations.AddField(
            model_name='shift',
            name='default_end_time',
            field=models.TimeField(blank=True, help_text='Default end time for this shift type', null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='default_start_time',
            field=models.TimeField(blank=True, help_text='Default start time for this shift type', null=True),
        ),
    ]
