# Generated by Django 4.2.9 on 2025-02-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_datespecificshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='ramadan_end_time',
            field=models.TimeField(blank=True, help_text='End time during Ramadan period', null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='ramadan_start_time',
            field=models.TimeField(blank=True, help_text='Start time during Ramadan period', null=True),
        ),
    ]
