# Generated by Django 4.2.9 on 2025-02-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_create_default_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='default_end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='default_start_time',
        ),
        migrations.AddField(
            model_name='shift',
            name='default_night_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='default_night_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_night_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datespecificshiftoverride',
            name='shift_type',
            field=models.CharField(choices=[('DEFAULT', 'Default Shift'), ('NIGHT', 'Night Shift'), ('OPEN', 'Open Shift')], default='NIGHT', help_text='Shift type to override', max_length=20),
        ),
        migrations.AlterField(
            model_name='shift',
            name='break_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='shift',
            name='grace_period',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('DEFAULT', 'Default Shift'), ('NIGHT', 'Night Shift'), ('OPEN', 'Open Shift')], max_length=10),
        ),
    ]
