# Generated by Django 4.2.9 on 2025-02-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_remove_shift_default_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='applicable_departments',
        ),
    ]
