# Generated by Django 4.2.9 on 2025-02-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_user'),
        ('attendance', '0014_remove_holiday_applicable_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBeginningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_days', models.DecimalField(decimal_places=2, help_text='Initial leave balance in days.', max_digits=6, verbose_name='Balance Days')),
                ('as_of_date', models.DateField(help_text='Date when this balance was recorded', verbose_name='As of Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beginning_balances', to='employees.employee', verbose_name='Employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.leavetype', verbose_name='Leave Type')),
            ],
            options={
                'verbose_name': 'Leave Beginning Balance',
                'verbose_name_plural': 'Leave Beginning Balances',
                'unique_together': {('employee', 'leave_type', 'as_of_date')},
            },
        ),
    ]
