# Generated by Django 4.2.9 on 2025-02-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_user'),
        ('attendance', '0015_leavebeginningbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='attendance.holiday'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply to all departments', related_name='holidays', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='source',
            field=models.CharField(choices=[('system', 'System'), ('manual', 'Manual'), ('holiday', 'Holiday')], default='system', max_length=20),
        ),
    ]
