# Generated by Django 4.2.9 on 2025-02-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_remove_holiday_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_sub_type',
            field=models.CharField(blank=True, help_text='Sub-type or specific category of the leave', max_length=50),
        ),
    ]
