# Generated by Django 4.2.9 on 2025-02-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_leave_leave_sub_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalanceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_number', models.PositiveIntegerField()),
                ('tier_name', models.CharField(max_length=50)),
                ('days_allowed', models.DecimalField(decimal_places=2, help_text='Number of days allowed in this tier', max_digits=6)),
                ('days_used', models.DecimalField(decimal_places=2, default=0, help_text='Number of days used from this tier', max_digits=6)),
                ('pay_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of salary paid for this tier', max_digits=5)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='attendance.leavebalance')),
            ],
            options={
                'ordering': ['tier_number'],
                'unique_together': {('balance', 'tier_number')},
            },
        ),
    ]
