# Generated by Django 4.2.9 on 2025-02-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_leavebalancetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='balance_calculation',
            field=models.CharField(choices=[('FIXED', 'Fixed Allowance'), ('ACCRUAL', 'Monthly Accrual'), ('TIERED', 'Tiered System'), ('SHARED', 'Shared Balance')], default='FIXED', help_text='How the leave balance is calculated', max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='shared_balance_with',
            field=models.ForeignKey(blank=True, help_text='For shared balance types, reference the main leave type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_leave_types', to='attendance.leavetype'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field for storing leave type specific validation rules'),
        ),
    ]
