# Generated by Django 4.2.9 on 2025-02-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_leavetype_balance_calculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='attendance.leave'),
        ),
    ]
